### ISSUE TITLE
error: org.freedesktop.Sdk/x86_64/18.08 not installed

### ISSUE THREAD

**Issue by nealmcb** [sa5bke/flatpak-openspace#1]
As a flatpak newbie, I may be out on a limb here, but I'm giving it a whirl.
I'm on Ubuntu 18.04.
I first followed these instructions: https://flatpak.org/setup/Ubuntu/

Then I did this also:

    sudo apt install flatpak-builder

Then I cloned this repo, and ran

    flatpak-builder --repo=. --force-clean build flatpak-openspace/com.openspaceproject.openspace.json

I got this error:

    error: org.freedesktop.Sdk/x86_64/18.08 not installed
    Failed to init: Unable to find sdk org.freedesktop.Sdk version 18.08

**Comment by sa5bke** [comment]
The README is now covering this.
